# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 381, 61))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(9, 9, 48, 16))
        self.label.setObjectName("label")
        self.COM_ComboBox = QtWidgets.QComboBox(self.widget)
        self.COM_ComboBox.setGeometry(QtCore.QRect(9, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.COM_ComboBox.setFont(font)
        self.COM_ComboBox.setObjectName("COM_ComboBox")
        self.ButaRate_ComboBox = QtWidgets.QComboBox(self.widget)
        self.ButaRate_ComboBox.setGeometry(QtCore.QRect(90, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.ButaRate_ComboBox.setFont(font)
        self.ButaRate_ComboBox.setEditable(False)
        self.ButaRate_ComboBox.setObjectName("ButaRate_ComboBox")
        self.OpenCom_PushButton = QtWidgets.QPushButton(self.widget)
        self.OpenCom_PushButton.setGeometry(QtCore.QRect(210, 30, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.OpenCom_PushButton.setFont(font)
        self.OpenCom_PushButton.setObjectName("OpenCom_PushButton")
        self.Close_PushButton = QtWidgets.QPushButton(self.widget)
        self.Close_PushButton.setGeometry(QtCore.QRect(270, 30, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Close_PushButton.setFont(font)
        self.Close_PushButton.setObjectName("Close_PushButton")
        self.Refresh_PushButton = QtWidgets.QPushButton(self.widget)
        self.Refresh_PushButton.setGeometry(QtCore.QRect(330, 30, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Refresh_PushButton.setFont(font)
        self.Refresh_PushButton.setObjectName("Refresh_PushButton")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(10, 70, 381, 101))
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(9, 9, 48, 16))
        self.label_2.setObjectName("label_2")
        self.RequestAll_PushButton = QtWidgets.QPushButton(self.widget_2)
        self.RequestAll_PushButton.setGeometry(QtCore.QRect(10, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RequestAll_PushButton.setFont(font)
        self.RequestAll_PushButton.setObjectName("RequestAll_PushButton")
        self.RequestAwake_PushButton = QtWidgets.QPushButton(self.widget_2)
        self.RequestAwake_PushButton.setGeometry(QtCore.QRect(120, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RequestAwake_PushButton.setFont(font)
        self.RequestAwake_PushButton.setObjectName("RequestAwake_PushButton")
        self.SerachCard_PushButton = QtWidgets.QPushButton(self.widget_2)
        self.SerachCard_PushButton.setGeometry(QtCore.QRect(10, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.SerachCard_PushButton.setFont(font)
        self.SerachCard_PushButton.setObjectName("SerachCard_PushButton")
        self.SerachedCard_TextEdit = QtWidgets.QTextEdit(self.widget_2)
        self.SerachedCard_TextEdit.setGeometry(QtCore.QRect(120, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.SerachedCard_TextEdit.setFont(font)
        self.SerachedCard_TextEdit.setObjectName("SerachedCard_TextEdit")
        self.Choose_PushButton = QtWidgets.QPushButton(self.widget_2)
        self.Choose_PushButton.setGeometry(QtCore.QRect(310, 70, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Choose_PushButton.setFont(font)
        self.Choose_PushButton.setObjectName("Choose_PushButton")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(10, 170, 381, 131))
        self.widget_3.setObjectName("widget_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(9, 9, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(50, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.KuaiAcess_TextEdit = QtWidgets.QTextEdit(self.widget_3)
        self.KuaiAcess_TextEdit.setGeometry(QtCore.QRect(130, 20, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.KuaiAcess_TextEdit.setFont(font)
        self.KuaiAcess_TextEdit.setObjectName("KuaiAcess_TextEdit")
        self.PasswordA_TextEdit = QtWidgets.QTextEdit(self.widget_3)
        self.PasswordA_TextEdit.setGeometry(QtCore.QRect(130, 60, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.PasswordA_TextEdit.setFont(font)
        self.PasswordA_TextEdit.setObjectName("PasswordA_TextEdit")
        self.PasswordB_TextEdit = QtWidgets.QTextEdit(self.widget_3)
        self.PasswordB_TextEdit.setGeometry(QtCore.QRect(130, 100, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.PasswordB_TextEdit.setFont(font)
        self.PasswordB_TextEdit.setObjectName("PasswordB_TextEdit")
        self.PasswordA_PushButton = QtWidgets.QPushButton(self.widget_3)
        self.PasswordA_PushButton.setGeometry(QtCore.QRect(20, 62, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PasswordA_PushButton.setFont(font)
        self.PasswordA_PushButton.setObjectName("PasswordA_PushButton")
        self.PasswordB_PushButton = QtWidgets.QPushButton(self.widget_3)
        self.PasswordB_PushButton.setGeometry(QtCore.QRect(20, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PasswordB_PushButton.setFont(font)
        self.PasswordB_PushButton.setObjectName("PasswordB_PushButton")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(10, 300, 381, 141))
        self.widget_4.setObjectName("widget_4")
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setGeometry(QtCore.QRect(9, 9, 61, 16))
        self.label_7.setObjectName("label_7")
        self.Read_PushButton = QtWidgets.QPushButton(self.widget_4)
        self.Read_PushButton.setGeometry(QtCore.QRect(10, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Read_PushButton.setFont(font)
        self.Read_PushButton.setObjectName("Read_PushButton")
        self.Write_PushButton = QtWidgets.QPushButton(self.widget_4)
        self.Write_PushButton.setGeometry(QtCore.QRect(10, 70, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Write_PushButton.setFont(font)
        self.Write_PushButton.setObjectName("Write_PushButton")
        self.Sleep_PushButton = QtWidgets.QPushButton(self.widget_4)
        self.Sleep_PushButton.setGeometry(QtCore.QRect(10, 110, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Sleep_PushButton.setFont(font)
        self.Sleep_PushButton.setObjectName("Sleep_PushButton")
        self.Read_TextEdit = QtWidgets.QTextEdit(self.widget_4)
        self.Read_TextEdit.setGeometry(QtCore.QRect(80, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Read_TextEdit.setFont(font)
        self.Read_TextEdit.setObjectName("Read_TextEdit")
        self.Write_TextEdit = QtWidgets.QTextEdit(self.widget_4)
        self.Write_TextEdit.setGeometry(QtCore.QRect(80, 70, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Write_TextEdit.setFont(font)
        self.Write_TextEdit.setObjectName("Write_TextEdit")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(10, 440, 381, 151))
        self.widget_5.setObjectName("widget_5")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setGeometry(QtCore.QRect(9, 9, 61, 16))
        self.label_8.setObjectName("label_8")
        self.Recharge_TextEdit = QtWidgets.QTextEdit(self.widget_5)
        self.Recharge_TextEdit.setGeometry(QtCore.QRect(80, 40, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Recharge_TextEdit.setFont(font)
        self.Recharge_TextEdit.setObjectName("Recharge_TextEdit")
        self.Deduction_TextEdit = QtWidgets.QTextEdit(self.widget_5)
        self.Deduction_TextEdit.setGeometry(QtCore.QRect(80, 80, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Deduction_TextEdit.setFont(font)
        self.Deduction_TextEdit.setObjectName("Deduction_TextEdit")
        self.RechargeAccept_PushButton = QtWidgets.QPushButton(self.widget_5)
        self.RechargeAccept_PushButton.setGeometry(QtCore.QRect(300, 40, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.RechargeAccept_PushButton.setFont(font)
        self.RechargeAccept_PushButton.setObjectName("RechargeAccept_PushButton")
        self.BalanceRequest_TextEdit = QtWidgets.QPushButton(self.widget_5)
        self.BalanceRequest_TextEdit.setGeometry(QtCore.QRect(300, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.BalanceRequest_TextEdit.setFont(font)
        self.BalanceRequest_TextEdit.setObjectName("BalanceRequest_TextEdit")
        self.DeductionAccept_PushButton = QtWidgets.QPushButton(self.widget_5)
        self.DeductionAccept_PushButton.setGeometry(QtCore.QRect(300, 80, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.DeductionAccept_PushButton.setFont(font)
        self.DeductionAccept_PushButton.setObjectName("DeductionAccept_PushButton")
        self.Balance_TextEdit = QtWidgets.QTextEdit(self.widget_5)
        self.Balance_TextEdit.setGeometry(QtCore.QRect(80, 120, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Balance_TextEdit.setFont(font)
        self.Balance_TextEdit.setObjectName("Balance_TextEdit")
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 54, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_5)
        self.label_10.setGeometry(QtCore.QRect(20, 80, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setGeometry(QtCore.QRect(20, 120, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.Text = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text.setGeometry(QtCore.QRect(400, 10, 381, 581))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Text.setFont(font)
        self.Text.setObjectName("Text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 23))
        self.menubar.setObjectName("menubar")
        self.menuISO_1443 = QtWidgets.QMenu(self.menubar)
        self.menuISO_1443.setObjectName("menuISO_1443")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuISO_1443.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "串口操作"))
        self.OpenCom_PushButton.setText(_translate("MainWindow", "打开"))
        self.Close_PushButton.setText(_translate("MainWindow", "关闭"))
        self.Refresh_PushButton.setText(_translate("MainWindow", "刷新"))
        self.label_2.setText(_translate("MainWindow", "寻卡操作"))
        self.RequestAll_PushButton.setText(_translate("MainWindow", "请求所有"))
        self.RequestAwake_PushButton.setText(_translate("MainWindow", "请求未休眠"))
        self.SerachCard_PushButton.setText(_translate("MainWindow", "寻卡"))
        self.Choose_PushButton.setText(_translate("MainWindow", " 选择"))
        self.label_3.setText(_translate("MainWindow", "认证操作"))
        self.label_6.setText(_translate("MainWindow", "块地址"))
        self.PasswordA_PushButton.setText(_translate("MainWindow", "认证密钥A"))
        self.PasswordB_PushButton.setText(_translate("MainWindow", "认证密钥B"))
        self.label_7.setText(_translate("MainWindow", "读写操作"))
        self.Read_PushButton.setText(_translate("MainWindow", "读取"))
        self.Write_PushButton.setText(_translate("MainWindow", "写入"))
        self.Sleep_PushButton.setText(_translate("MainWindow", "休眠"))
        self.label_8.setText(_translate("MainWindow", "电子钱包"))
        self.RechargeAccept_PushButton.setText(_translate("MainWindow", "确定"))
        self.BalanceRequest_TextEdit.setText(_translate("MainWindow", "查询"))
        self.DeductionAccept_PushButton.setText(_translate("MainWindow", "确定"))
        self.label_9.setText(_translate("MainWindow", "充值"))
        self.label_10.setText(_translate("MainWindow", "扣费"))
        self.label_11.setText(_translate("MainWindow", "余额"))
        self.menuISO_1443.setTitle(_translate("MainWindow", "ISO 1443 模块"))
